### ISSUE TITLE
add a simple function to allow an R script to auto-spin itself

### ISSUE THREAD

**Issue by daattali** [daattali/rsalad#3]
I came up with this very useful little snippet that I like to add to the top of scripts.  It enables me to "source" the script and result in a markdown format of the output, while avoiding running the code twice.

```
#+ spinme, eval = FALSE, echo = FALSE
SCRIPT_NAME <- "scriptname.R"
spin(SCRIPT_NAME, knit = TRUE)
try(stop(), silent = TRUE)
#+ eval = TRUE, echo = TRUE
```

Either share this knowledge somewhere (r-bloggers?) or add a function that will add this snippet to a file

**Comment by daattali** [comment]
to get file name:  
`file <- basename(sys.frame(1)$ofile)`

**Comment by daattali** [comment]
update:
```
#+ spinme-chunk, eval = FALSE, echo = FALSE
.scriptName <- basename(sys.frame(1)$ofile)
.spinOutput <- knitr::spin(.scriptName, knit = TRUE)
stop(sprintf("Ignore this error - your output is ready at:\n%s",
             normalizePath(.spinOutput)),
     call. = FALSE)
#+ spinme-done, eval = TRUE, echo = TRUE
```

**Comment by daattali** [comment]
update: safer way to get filename (only works if file is "source"-ed

```
gethisfilename <- function() {
  x <- eval(match.call()[[1]])
  getSrcFilename(x)
}
filename <- gethisfilename()
if (filename == ".active-rstudio-document"){
  stop("Please save your script before running \"Source\".",
       call. = FALSE)
}
if (filename == "") {
  stop("Please either use the RStudio \"Source\" button, or set the script's name.",
       call. = FALSE)
}
```

**Comment by krlmlr** [comment]
Yet another way to get the filename: `kimisc::thisfile()` ;-)

**Comment by daattali** [comment]
That seems like a robust function Ill take a closer look when i get around to adding this officially thanks!

**Comment by daattali** [comment]
moving this issue to daattali/ezknitr#2
